### ISSUE TITLE
Declaration of Djoudi\LaravelH5p\Repositories\LaravelH5pRepository::setErrorMessage($message) must be compatible with H5PFrameworkInterface::setErrorMessage($message, $code = NULL)

### ISSUE THREAD

**Issue by codebox2019** [djoudi/Laravel-H5P#12]
Hi,
I am having following error when i try to access to url.

ERROR IMAGE: http://prntscr.com/n0x59o

Thanks

**Comment by djoudi** [comment]
Hi @codebox2019
witch url exact ?

**Comment by saguu6** [comment]
Hi,
Even am getting the same error.
**Declaration of Djoudi\LaravelH5p\Repositories\LaravelH5pRepository::getNumContent($library_id) must be compatible with H5PFrameworkInterface::getNumContent($libraryId, $skip = NULL)**

Can you please help me out in this.
Thanks

**Comment by dailez** [comment]
The url is /create

**Comment by djoudi** [comment]
solved

**Comment by pidab** [comment]
> solved

In what way has this issue been solved? I'm still getting the same error about `H5PFrameworkInterface` when trying to install this package with `composer require`, which uses version 1.0 (which in turn requires Laravel 5.5). This happens at both `/hp5/create` and `/hp5/library`. I had a little more success using version 2.0 of this package with Laravel 5.8, but didn't manage to upload a library or create a content yet.

**Comment by nitingohel** [comment]
I am getting this error while create the h5p

Declaration of Djoudi\LaravelH5p\Repositories\LaravelH5pRepository::setErrorMessage($message) must be compatible with H5PFrameworkInterface::setErrorMessage($message, $code = NULL)

Anyone please help
