### ISSUE TITLE
Not working with latest h5p-php-library

### ISSUE THREAD

**Issue by dailez** [djoudi/Laravel-H5P#22]
It seems that this library is not working with the latest h5p-php-library (1.22). Could you either freeze the h5p-library version or update the code (add the missing interface implementations)? Many thanks in advance

**Comment by djoudi** [comment]
solved

**Comment by dailez** [comment]
Unfortunately not yet working on my PC. Opening /create does not show the h5p editor. I use Laravel 5.8, PHP 7.1 and Windows. This is what I see:

![Laravel-2019-07-23-07-07-65](https://user-images.githubusercontent.com/6159851/61684296-3ff02080-ad19-11e9-9a13-d11517959f69.png)

On /h5p the menu on the top right is also now visible: See ...

![Laravel-2019-07-23-07-07-30](https://user-images.githubusercontent.com/6159851/61684372-99f0e600-ad19-11e9-8b9c-89813eae824d.png)

Can you reproduce the error?

**Comment by dailez** [comment]
I think the problem of the startpage has to do with Bootstrap. Laravel 5.8 uses Bootstrap v4 and I think you are using v3.3.

**Comment by lhestdave** [comment]
> Unfortunately not yet working on my PC. Opening /create does not show the h5p editor. I use Laravel 5.8, PHP 7.1 and Windows. This is what I see:
> 
> ![Laravel-2019-07-23-07-07-65](https://user-images.githubusercontent.com/6159851/61684296-3ff02080-ad19-11e9-9a13-d11517959f69.png)
> 
> On /h5p the menu on the top right is also now visible: See ...
> 
> ![Laravel-2019-07-23-07-07-30](https://user-images.githubusercontent.com/6159851/61684372-99f0e600-ad19-11e9-8b9c-89813eae824d.png)
> 
> Can you reproduce the error?

populate the db and use the correct version of h5p-core/editor

**Comment by djoudi** [comment]
first you can upload library  /library
