### ISSUE TITLE
Why is this create h5p page laravel-h5p.content.parameters show undefined

### ISSUE THREAD

**Issue by zw12579** [djoudi/Laravel-H5P#5]
![show undefined image](https://github.com/zw12579/image/blob/master/12.png)

**Comment by djoudi** [comment]
sorry i do'nt see this error

**Comment by dailez** [comment]
The error still exists. See screenshot for more details. Before loading the parameters drop down, there is a text saying: Missing translation for library core. 

![Laravel-2019-07-23-07-07-65](https://user-images.githubusercontent.com/6159851/61684219-fbfd1b80-ad18-11e9-9199-60981d7994c8.png)

**Comment by dailez** [comment]
If fixed the Bootstrap issue (downgrade to v3.3.7) but the problems with the parameters still exist:

![Laravel-2019-07-23-07-07-65](https://user-images.githubusercontent.com/6159851/61686071-eab70d80-ad1e-11e9-80ef-a9ae89ce58b8.png)
